"""test JWT tokens

Revision ID: 210205a9e98c
Revises: 74206bd9bb40
Create Date: 2025-03-06 14:07:30.984806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210205a9e98c'
down_revision: Union[str, None] = '74206bd9bb40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('decoded_token_info', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'decoded_token_info')
    # ### end Alembic commands ###
