"""create workout_log table

Revision ID: 2585422972db
Revises: 8170b9d22565
Create Date: 2025-03-10 18:45:23.853686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2585422972db'
down_revision: Union[str, None] = '8170b9d22565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'workout_log',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('exercise', sa.String(), nullable=False),
        sa.Column('sets', sa.Integer(), nullable=False),
        sa.Column('reps', sa.Integer(), nullable=False),
        sa.Column('weight', sa.Float(), nullable=True),
        sa.Column('mood', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_log')
    # ### end Alembic commands ###
