"""health data model

Revision ID: 3bf8ae932951
Revises: c756f3f78652
Create Date: 2025-03-23 17:35:13.965034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bf8ae932951'
down_revision: Union[str, None] = 'c756f3f78652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'health_datas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('steps', sa.Integer(), nullable=False, default=0),
        sa.Column('calories_burnt', sa.Integer(), nullable=False, default=0),
        sa.Column('avg_heart_rate', sa.Integer(), nullable=True),
        sa.Column('sleep_duration', sa.Integer(), nullable=True),
        sa.Column('active_mins', sa.Integer(), nullable=False, default=0),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')
    )
    op.create_index(op.f('ix_health_datas_id'), 'health_datas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_datas_id'), table_name='health_datas') 
    op.drop_table('health_datas')
    # ### end Alembic commands ###
