"""create workout_logs

Revision ID: 43cc7268dfae
Revises: e231cf41101d
Create Date: 2025-03-16 21:12:24.091745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43cc7268dfae'
down_revision: Union[str, None] = 'e231cf41101d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the workout_logs table
    op.create_table(
        'workout_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('type', sa.Enum('Voice', 'Manual', name='log_method'), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('duration_minutes', sa.Integer(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=True, default=sa.func.now()),
        sa.Column('mood', sa.Enum('ENERGIZED', 'TIRED', 'MOTIVATED', 'STRESSED', 'NEUTRAL', name='mood_type'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')  # Foreign key reference to users table
    )

    # Create exercises table to store exercise details for each workout log
    op.create_table(
        'exercises',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('workout_log_id', sa.Integer(), sa.ForeignKey('workout_logs.id', ondelete='CASCADE'), nullable=False),
        sa.Column('exercise_name', sa.String(), nullable=False),
        sa.Column('sets', sa.Integer(), nullable=False),
        sa.Column('reps', sa.Integer(), nullable=False),
        sa.Column('weight', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_index(op.f('ix_exercises_workout_log_id'), 'exercises', ['workout_log_id'], unique=False)

    op.create_index(op.f('ix_workout_logs_id'), 'workout_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_workout_log_id'), table_name='exercises')
    op.drop_table('exercises')

    op.drop_index(op.f('ix_workout_logs_id'), table_name='workout_logs')
    op.drop_table('workout_logs')
    # ### end Alembic commands ###
