"""create workout_log table

Revision ID: 7fcf8c19cf91
Revises: 8170b9d22565
Create Date: 2025-03-10 21:06:24.992545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fcf8c19cf91'
down_revision: Union[str, None] = '8170b9d22565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('type', sa.Enum('Voice', 'Manual', name='log_method'), nullable=False),
        sa.Column('exercise_details', sa.JSON(), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('duration_minutes', sa.Integer(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=True, default=sa.func.now()),
        sa.Column('mood', sa.Enum('Energized', 'Tired', 'Motivated', 'Stressed', 'Neutral', name='mood_type'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')  # Foreign key reference to users table
    )
    op.create_index(op.f('ix_workout_log_id'), 'workout_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_log_id'), table_name='workout_log')
    op.drop_table('workout_log')
    # ### end Alembic commands ###
