"""store hashed refresh tokens

Revision ID: 94423f9a34aa
Revises: c2a13bd242e3
Create Date: 2025-03-07 11:57:53.204934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94423f9a34aa'
down_revision: Union[str, None] = 'c2a13bd242e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_refresh_token')
    # ### end Alembic commands ###
