"""test JWT token

Revision ID: b087e43d76a9
Revises: e58535ca249a
Create Date: 2025-03-06 14:14:47.996891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b087e43d76a9'
down_revision: Union[str, None] = 'e58535ca249a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'decoded_token_info')
    op.drop_column('users', 'JWT_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('JWT_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('decoded_token_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
