"""messages url

Revision ID: bc690f305cf7
Revises: 2d8449f790e3
Create Date: 2025-05-15 23:26:50.187036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc690f305cf7'
down_revision: Union[str, None] = '2d8449f790e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("messages",sa.Column("image_url",sa.String(),nullable=True))
    op.alter_column("messages",sa.Column("content",sa.String(),nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("messages",sa.Column("content",sa.String(),nullable=False))
    op.drop_column("messages","image_url")