"""adding columns to ai model

Revision ID: c48a4dc90eb3
Revises: 3bf8ae932951
Create Date: 2025-04-01 14:59:59.574626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c48a4dc90eb3'
down_revision: Union[str, None] = '3bf8ae932951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_advices', sa.Column('workout_earliest_date',sa.DateTime(), nullable=True)),
    op.add_column('ai_advices', sa.Column('workout_latest_date',sa.DateTime(), nullable=True)),
    op.add_column('ai_advices', sa.Column('contains_health_data',sa.Boolean, nullable=True)),
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_advices', 'contains_health_data')
    op.drop_column('ai_advices', 'workout_latest_date')
    op.drop_column('ai_advices', 'workout_earliest_date')
    # ### end Alembic commands ###