"""adding weight

Revision ID: c756f3f78652
Revises: cca838310d91
Create Date: 2025-03-20 21:31:54.741786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c756f3f78652'
down_revision: Union[str, None] = 'cca838310d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('users', sa.Column('weight', sa.Integer(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weight')
    
    # ### end Alembic commands ###
