"""ai model

Revision ID: cca838310d91
Revises: e5708e9c94b5
Create Date: 2025-03-19 00:40:49.206154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cca838310d91'
down_revision: Union[str, None] = 'e5708e9c94b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Define Enum values manually
ai_advice_type_enum = sa.Enum(
    "WORKOUT_ADVICE",
    "WORKOUT_OPTIMIZATION",
    "RECOVERY_ANALYSIS",
    "PERFORMANCE_TRENDS",
    "MUSCLE_BALANCE",
    "GOAL_ALIGNMENT",
    name="ai_advice_type"
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ai_advices',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('advice_type', ai_advice_type_enum, nullable=False),
        sa.Column('ai_feedback', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')
    )
    op.create_index(op.f('ix_ai_advices_id'), 'ai_advices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_advices_id'), table_name='ai_advices')    
    op.drop_table('ai_advices')
    # ### end Alembic commands ###
